### ISSUE TITLE
[Bug]typename llvm::Value, llvm::Constant* argument of incompatible type!

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/elz#11]
### Problem you meet
As title, incompatible type, need to read LLVM doc then rewrite that.
### Error Log
```
elz: ../../../../../include/llvm/Support/Casting.h:255: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::Constant; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Constant*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
SIGABRT: abort
PC=0x7fc76fe19428 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x541db0, 0xc4200f1d80, 0x2865ce8)
	/usr/lib/go-1.9/src/runtime/cgocall.go:132 +0xe4 fp=0xc4200f1d50 sp=0xc4200f1d10 pc=0x419894
llvm.org/llvm/bindings/go/llvm._Cfunc_LLVMConstFMul(0x2865c10, 0x2867ee8, 0x0)
	llvm.org/llvm/bindings/go/llvm/_obj/_cgo_gotypes.go:2853 +0x4e fp=0xc4200f1d80 sp=0xc4200f1d50 pc=0x4f433e
llvm.org/llvm/bindings/go/llvm.ConstFMul.func1(0x2865c10, 0x2867ee8, 0x2865110)
	/home/routedan/workspace/go/src/llvm.org/llvm/bindings/go/llvm/ir.go:870 +0xa3 fp=0xc4200f1db8 sp=0xc4200f1d80 pc=0x4f6853
llvm.org/llvm/bindings/go/llvm.ConstFMul(0x2865c10, 0x2867ee8, 0x2867ee8)
	/home/routedan/workspace/go/src/llvm.org/llvm/bindings/go/llvm/ir.go:870 +0x35 fp=0xc4200f1de0 sp=0xc4200f1db8 pc=0x4f5a05
github.com/elz-lang/elz/ast.(*BinaryExpr).Codegen(0xc420133080, 0xc420132fc0, 0xc42011e3d4)
	/home/routedan/workspace/go/src/github.com/elz-lang/elz/ast/expr.go:41 +0x12c fp=0xc4200f1e30 sp=0xc4200f1de0 pc=0x4f758c
github.com/elz-lang/elz/ast.(*VarDefination).Codegen(0xc420126f80, 0xc420132fc0, 0x2867e28)
	/home/routedan/workspace/go/src/github.com/elz-lang/elz/ast/ast.go:34 +0xb5 fp=0xc4200f1e88 sp=0xc4200f1e30 pc=0x4f70e5
github.com/elz-lang/elz/listener.(*ElzListener).Module(0xc420126ec0, 0x90c0c0)
	/home/routedan/workspace/go/src/github.com/elz-lang/elz/listener/listener.go:27 +0x5b fp=0xc4200f1ef0 sp=0xc4200f1e88 pc=0x53c62b
main.main()
	/home/routedan/workspace/go/src/github.com/elz-lang/elz/main.go:23 +0x203 fp=0xc4200f1f80 sp=0xc4200f1ef0 pc=0x53f553
runtime.main()
	/usr/lib/go-1.9/src/runtime/proc.go:195 +0x226 fp=0xc4200f1fe0 sp=0xc4200f1f80 pc=0x441776
runtime.goexit()
	/usr/lib/go-1.9/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4200f1fe8 sp=0xc4200f1fe0 pc=0x46a501

rax    0x0
rbx    0x7fc7748da000
rcx    0x7fc76fe19428
rdx    0x6
rdi    0x2b76
rsi    0x2b76
rbp    0x7fc770ebb0f8
rsp    0x7ffcd4dcc638
r8     0xfefefefefefefeff
r9     0x1
r10    0x8
r11    0x202
r12    0xff
r13    0x7fc770ee46e0
r14    0x13
r15    0xc
rip    0x7fc76fe19428
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
```

**Comment by dannypsnl** [comment]
Solved by logged value of constant, not it's IR
